#!/bin/bash

################################################################################
# Cron Job Setup Script
#
# Installs cron jobs for automated backups and maintenance
################################################################################

set -euo pipefail

LOG_FILE="/var/log/setup-cron.log"
DRY_RUN=false

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') [$1] ${@:2}" | tee -a "$LOG_FILE"; }

show_usage() {
    cat << EOF
Cron Job Setup Script

Usage: sudo $0 [options]

Options:
    --help              Show help
    --dry-run           Show what would be installed
    --remove            Remove cron jobs

Description:
    Installs cron jobs for automated backups:
    - Full backup: Daily at 2 AM
    - Incremental backup: Every 6 hours
    - PITR base backup: Weekly (Sunday 1 AM)
    - Backup verification: Weekly (Saturday 3 AM)
    - Backup cleanup: Daily at 4 AM
    - Recovery test: Monthly (1st at 5 AM)

EOF
    exit 0
}

REMOVE_MODE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --help) show_usage ;;
        --dry-run) DRY_RUN=true; shift ;;
        --remove) REMOVE_MODE=true; shift ;;
        *) log "ERROR" "Unknown option: $1"; show_usage ;;
    esac
done

if [[ $EUID -ne 0 ]] && [[ $DRY_RUN == false ]]; then
    log "ERROR" "Must run as root"
    exit 1
fi

SCRIPTS_DIR="/var/www/event-manager/scripts"
CRON_FILE="/etc/cron.d/event-manager-backup"

remove_cron_jobs() {
    log "INFO" "Removing cron jobs..."

    if [[ $DRY_RUN == true ]]; then
        log "INFO" "[DRY-RUN] Would remove: $CRON_FILE"
        return 0
    fi

    if [[ -f "$CRON_FILE" ]]; then
        rm -f "$CRON_FILE"
        log "SUCCESS" "Cron jobs removed"
    else
        log "INFO" "No cron jobs to remove"
    fi
}

install_cron_jobs() {
    log "INFO" "Installing cron jobs..."

    if [[ $DRY_RUN == true ]]; then
        log "INFO" "[DRY-RUN] Would install cron jobs to: $CRON_FILE"
        cat << 'EOF'

# Event Manager Backup Cron Jobs

# Full backup - Daily at 2 AM
0 2 * * * root /var/www/event-manager/scripts/backup-full.sh >> /var/log/backup-full.log 2>&1

# Incremental backup - Every 6 hours
0 */6 * * * root /var/www/event-manager/scripts/backup-incremental.sh >> /var/log/backup-incremental.log 2>&1

# PITR base backup - Weekly on Sunday at 1 AM
0 1 * * 0 root /var/www/event-manager/scripts/pitr-base-backup.sh >> /var/log/pitr-backup.log 2>&1

# Backup verification - Weekly on Saturday at 3 AM
0 3 * * 6 root /var/www/event-manager/scripts/backup-verify.sh >> /var/log/backup-verify.log 2>&1

# Backup cleanup - Daily at 4 AM
0 4 * * * root /var/www/event-manager/scripts/backup-cleanup.sh >> /var/log/backup-cleanup.log 2>&1

# Recovery test - Monthly on 1st at 5 AM
0 5 1 * * root /var/www/event-manager/scripts/test-recovery.sh >> /var/log/recovery-test.log 2>&1

EOF
        return 0
    fi

    cat > "$CRON_FILE" << 'EOF'
# Event Manager Backup Cron Jobs
# Generated by setup-cron.sh

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Full backup - Daily at 2 AM
0 2 * * * root /var/www/event-manager/scripts/backup-full.sh >> /var/log/backup-full.log 2>&1

# Incremental backup - Every 6 hours
0 */6 * * * root /var/www/event-manager/scripts/backup-incremental.sh >> /var/log/backup-incremental.log 2>&1

# PITR base backup - Weekly on Sunday at 1 AM
0 1 * * 0 root /var/www/event-manager/scripts/pitr-base-backup.sh >> /var/log/pitr-backup.log 2>&1

# Backup verification - Weekly on Saturday at 3 AM
0 3 * * 6 root /var/www/event-manager/scripts/backup-verify.sh >> /var/log/backup-verify.log 2>&1

# Backup cleanup - Daily at 4 AM
0 4 * * * root /var/www/event-manager/scripts/backup-cleanup.sh >> /var/log/backup-cleanup.log 2>&1

# Recovery test - Monthly on 1st at 5 AM
0 5 1 * * root /var/www/event-manager/scripts/test-recovery.sh >> /var/log/recovery-test.log 2>&1

EOF

    chmod 644 "$CRON_FILE"
    log "SUCCESS" "Cron jobs installed: $CRON_FILE"

    # Restart cron service
    systemctl restart cron || systemctl restart crond || true
    log "SUCCESS" "Cron service restarted"
}

verify_installation() {
    log "INFO" "Verifying installation..."

    # Check if scripts exist and are executable
    local scripts=(
        "backup-full.sh"
        "backup-incremental.sh"
        "pitr-base-backup.sh"
        "backup-verify.sh"
        "backup-cleanup.sh"
        "test-recovery.sh"
    )

    for script in "${scripts[@]}"; do
        local script_path="${SCRIPTS_DIR}/${script}"
        if [[ -x "$script_path" ]]; then
            log "SUCCESS" "✓ $script"
        else
            log "WARNING" "✗ $script (not found or not executable)"
        fi
    done

    # Show next scheduled runs
    log "INFO" ""
    log "INFO" "Next scheduled runs:"
    log "INFO" "  Full backup:         Daily at 02:00"
    log "INFO" "  Incremental backup:  Every 6 hours"
    log "INFO" "  PITR base backup:    Sundays at 01:00"
    log "INFO" "  Backup verification: Saturdays at 03:00"
    log "INFO" "  Backup cleanup:      Daily at 04:00"
    log "INFO" "  Recovery test:       1st of month at 05:00"
}

main() {
    log "INFO" "=========================================="
    log "INFO" "Cron Job Setup"
    log "INFO" "=========================================="

    if [[ $REMOVE_MODE == true ]]; then
        remove_cron_jobs
    else
        install_cron_jobs
        [[ $DRY_RUN == false ]] && verify_installation
    fi

    log "INFO" "=========================================="
    log "SUCCESS" "Setup completed"
    log "INFO" "=========================================="
}

trap 'log "ERROR" "Setup failed at line $LINENO"; exit 1' ERR

main

exit 0
